apiVersion: apps/v1
kind: Deployment
metadata:
  name: agent-reasoning
spec:
  template:
    spec:
      containers:
        - name: agent-reasoning
          image: 792373136340.dkr.ecr.us-west-2.amazonaws.com/opsera/ai-tutor-agent-reasoning:dev-af80b3e-20260701122929
