apiVersion: apps/v1
kind: Deployment
metadata:
  name: analytics
spec:
  template:
    spec:
      containers:
        - name: analytics
          image: 792373136340.dkr.ecr.us-west-2.amazonaws.com/opsera/ai-tutor-analytics:dev-e9fd2ed-20260701180218
