apiVersion: apps/v1
kind: Deployment
metadata:
  name: assessment
spec:
  template:
    spec:
      containers:
        - name: assessment
          image: 792373136340.dkr.ecr.us-west-2.amazonaws.com/opsera/ai-tutor-assessment:dev-aad8a7a-20260701130909
