apiVersion: apps/v1
kind: Deployment
metadata:
  name: audit
spec:
  template:
    spec:
      containers:
        - name: audit
          image: 792373136340.dkr.ecr.us-west-2.amazonaws.com/opsera/ai-tutor-audit:dev-f738904-20260721181730
