apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-orchestrator
spec:
  template:
    spec:
      containers:
        - name: chat-orchestrator
          image: 792373136340.dkr.ecr.us-west-2.amazonaws.com/opsera/ai-tutor-chat-orchestrator:dev-19c288f-20260702202348
