apiVersion: apps/v1
kind: Deployment
metadata:
  name: confidence-grader
spec:
  template:
    spec:
      containers:
        - name: confidence-grader
          image: 792373136340.dkr.ecr.us-west-2.amazonaws.com/opsera/ai-tutor-confidence-grader:dev-dd56058-20260701124356
