apiVersion: apps/v1
kind: Deployment
metadata:
  name: content-management
spec:
  template:
    spec:
      containers:
        - name: content-management
          image: 792373136340.dkr.ecr.us-west-2.amazonaws.com/opsera/ai-tutor-content-management:dev-1459d83-20260702140757
