apiVersion: apps/v1
kind: Deployment
metadata:
  name: learner-profile
spec:
  template:
    spec:
      containers:
        - name: learner-profile
          image: 792373136340.dkr.ecr.us-west-2.amazonaws.com/opsera/ai-tutor-learner-profile:dev-e9fd2ed-20260701180214
